# Generated by Django 4.2.5 on 2023-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="info",
            name="image",
        ),
        migrations.RemoveField(
            model_name="info",
            name="video",
        ),
        migrations.AddField(
            model_name="info",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="files/%y/%m/%d"),
        ),
    ]
