# Generated by Django 4.2.5 on 2023-10-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_info_image_remove_info_video_info_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="file",
            new_name="image",
        ),
        migrations.AddField(
            model_name="info",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/%y/%m/%d"),
        ),
    ]
