# Generated by Django 4.2.5 on 2023-10-15 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_file_info_image_info_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="image",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="info",
            name="video",
        ),
    ]
