# Generated by Django 4.2.5 on 2023-10-18 09:31

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
        migrations.RemoveField(
            model_name="document",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
