# Generated by Django 4.2.5 on 2023-10-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("word", "0003_document_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
